### ISSUE TITLE
WW frequency not picked up correctly from config data for medtronic pump

### ISSUE THREAD

**Issue by ToreBj** [andyrozman/RileyLinkAAPS#100]
When setting WW frequency (868 Mhz) for pump the tuning starts with 915 Mhz instead. After restart it correctly picks up the tuning with 868 Mhz and connects.

**Comment by andyrozman** [comment]
This should be fixed in 0.5. Please check if it works for you.

**Comment by ToreBj** [comment]
I tested your branch which was pulled yesterday and it worked perfectly!
