### ISSUE TITLE
When Bolus is delivering, pump doesn't respond to any Set commands

### ISSUE THREAD

**Issue by andyrozman** [andyrozman/RileyLinkAAPS#104]
When Bolus is delivering, pump doesn't respond to any Set commands.

I will have to add functionality to block Queue processing, so that no other commands are send to pump.

**Comment by andyrozman** [comment]
To fix this we will make pumpInterface set to busy for determined time, for that we need time that bolus is delivered:

test results for 715 ver 2.3A (Kuba @kubatom)
1U 37.99 36.93 36.59
5U 3:17.79 3:18.38 3:18.31
10U 6:39.07 6:38.36 6:39.01

rustymonkey @rustymonkey 
Bolus test results with a 722:
1u: 39, 40, 38
5u: 3:19.5, 3:20, 3:20.5
10u: 6:39, 6:41, 6:40

Mario @Alamo04 Mar 02 00:39
Here is the Bolus test with 522 and 754.
522:
1U = 39s, 38:51s, 38:33
5U = 3:18 min., 3:19, 3:17
10U = 6:37 min., 6:38, 6:38

754:
1U = 40s, 39s, 38S
5U = 3:24 min., 3:22, 3:18
10U = 5:06 min., 5:00, 4:59

**Comment by kubatom** [comment]
@andyrozman is there anything else that you need? Is there anything that we can help / assist with?
