### ISSUE TITLE
Add support for Superbolus

### ISSUE THREAD

**Issue by peterlynton** [andyrozman/RileyLinkAAPS#107]
Testing using medtronic_andy: when using Superbolus a message appears: 'Operation is not supported by pump and/or driver'.  Pump will continue with calculated (super)bolus but will not set a TBR of 0% for two hours as it should.  I'm unsure if this can be implemented in the pump driver?

**Comment by libxmike** [comment]
are you using 512/712 ? they don't support (e)SMB

**Comment by andyrozman** [comment]
It should be supported. On any pump. This is not OpenAPS. Any Pump should support SMB. Can you please see what is in the logs? Some command was called that was not implemented.

**Comment by peterlynton** [comment]
@andyrozman @libxmike
[AndroidAPS.log](https://github.com/andyrozman/RileyLinkAAPS/files/2867145/AndroidAPS.log)
 This is for a Superbolus, not SMB - SMB are running fine on both 722 and 723.

Log attached, wizard used to calculate Superbolus at 22:54:07.379, and failing in setting 0% basal for 120min at 22:54:10.042.

**Comment by andyrozman** [comment]
As we discovered this is AAPS core bug, so I am closing this one and Bug on AAPS was opened to fix this (they send wrong type of TBR to pump).
