### ISSUE TITLE
AAPS Crashes when processing UnabsorbedInsulin entries  

### ISSUE THREAD

**Issue by ElyeM** [andyrozman/RileyLinkAAPS#116]
It crashes at  PumpHistoryResult.java                      
` if (DateTimeUtil.getYear(unprocessedEntry.atechDateTime) != 2000)` atechDateTime is null

I see that UnabsorbedInsulin entryType It is not getting decoded but it is getting marked as `RecordDecodeStatus.OK` should it be marked `RecordDecodeStatus.Ignored` or it does need to get decoded?

**Comment by andyrozman** [comment]
Done and released 0.9
