### ISSUE TITLE
Calibration problem for RL V2 devices

### ISSUE THREAD

**Issue by andyrozman** [andyrozman/RileyLinkAAPS#128]
This was reported by @rumil , he noticed that calibration doesn't work correctly. 

This is his proposed fix, but it needs to be extended, because implemented in this way it will break V1.
https://gist.github.com/rumil/75182286360ef40864e8147223b577d2

**Comment by rumil** [comment]
Confirming latest changes (rev 6d771d891858220231711ea7f42fddce8426debb) work fine (tune fine) with RL V2
