### ISSUE TITLE
Bolusing via calculator, get stuck at "waiting for pump"

### ISSUE THREAD

**Issue by stefanhubmer** [andyrozman/RileyLinkAAPS#135]
Using MDT_0.9 and Sony XZ1 Compact (Android 9)

When bolusing via calculator it sometimes get stuck at the "waiting for pump" popup. The "stop" button is not responding. Workaround: Close app and open it back again.
Pump is bolusing the correct amount.

As far as I can tell, the loop stops until you restart the app. Will update if I have more info

[Screenshot](https://user-images.githubusercontent.com/28067842/59354127-bd8d3d80-8d24-11e9-9533-d701f8514dd0.png)

Logs: [AndroidAPS._2019-06-12_00-00_.zip](https://github.com/andyrozman/RileyLinkAAPS/files/3281499/AndroidAPS._2019-06-12_00-00_.zip)
Bolus given at 14:45

**Comment by andyrozman** [comment]
What is for you stuck? There is certain amount of time (in s) that we wait before issuing the bolus. But stop should work...

**Comment by andyrozman** [comment]
Process goes like this:
1. Trying to contact pump (this can be repeated up to 3 times, with 30 s of timeout each time
2. When pump is contacted we wait specific time (5/10/15 s, depending on configuration)
3. Bolus is issued.

Before step 3, cancel should be possible... 

Looking at your log there is only one Bolus issued, and that was successful... (14:45:08)

**Comment by stefanhubmer** [comment]
Happened two times before and I'm using your MDT branch since five days.
Calculated, bolused, bolus given, stuck. Waited about 5 minutes (screen stayed as seen on screenshot), then killed the app.
After step 3, the popup didn't disappeared.

**Comment by andyrozman** [comment]
It works good for everybody else... What kind of phone do you have?

**Comment by stefanhubmer** [comment]
Sony G8441 XZ1 Compact (Android 9.0)
I'll take care of it and watch if it happens again in the next days. atm I can't give more infos

**Comment by andyrozman** [comment]
@stefanhubmer Do you still get this problems with never releases 0.10 (stable) or 0.11.1 (latest working dev)

**Comment by stefanhubmer** [comment]
@andyrozman Was using 0.10 about 2 days and got the same problem once. Unfortunately I'm on holiday and not using the MDT Branch atm, I'm going to start using back again at monday (1.7.) evening. If possible you can keep the ticket in backlog.

**Comment by andyrozman** [comment]
Sure... When you come please upgrade to latest version... If last release performs, I might make release over weekend... (0.11)...

**Comment by stefanhubmer** [comment]
Short update: unfortunately had no time to test, started yesterday with R0.11
Everythings smooth, I'm going to use it for two more days and if the bug won't appear again, I'll close the ticket.

**Comment by andyrozman** [comment]
Please try with medtronic_andy_merge branch... that is the latest version... It should show as 2.4-dev...

**Comment by stefanhubmer** [comment]
No issues with R0.11 (tested 2 days) and no issues with 2.4-dev (tested 3 days).
Used calculator 3-4 times every day.
Will close the ticket now
