### ISSUE TITLE
Medronic 723: Basal profiles are not enabled on pump

### ISSUE THREAD

**Issue by rkresha** [andyrozman/RileyLinkAAPS#158]
I'm getting the following 'urgent' alert the first communication happens between AAPS and Rileylink. I have 3 basal settings enabled on the pump so I'm not sure what it is complaining about. Please advise and let me know what I can do to assist. I'm currently using the dev branch from the main AAPS github repo.

-Rob

**Comment by jroth-haj** [comment]
AAPS ist only using the first basal profile.
Select the first profile!
Then so a Profile Switch in AAPS.
It will transfer your current selected profile to the pump.


Rob Kresha <notifications@github.com> schrieb am Mo., 23. Sept. 2019, 22:18:

**Comment by rkresha** [comment]
@jroth-haj I'm using the 'simple profile' profile if that makes a difference, however I'm not sure I follow what you suggesting I should do, could you please reword it?

**Comment by rkresha** [comment]
Switched over to local profile and did an activate profile and then a switch profile. I hit  'refresh' and get the same urgent alert

**Comment by rkresha** [comment]
Error message adjusted to be more intuitive for what the fix is.
