### ISSUE TITLE
Set Bolus - 754 Pump

### ISSUE THREAD

**Issue by alternateal** [andyrozman/RileyLinkAAPS#39]
Bolus was not set - and displayed on phone as not set

07-05 17:36:17.850 8059-8250/com.gxwtech.roundtrip2 I/ShowAAPS2Activity: [Thread-4] INFO  [com.gxwtech.roundtrip2.ShowAAPS2Activity$4:386]: start Action: Set Bolus
07-05 17:36:17.851 8059-8250/com.gxwtech.roundtrip2 D/MedtronicCommunicationManager: [Thread-4] DEBUG [info.nightscout.androidaps.plugins.PumpMedtronic.comm.MedtronicCommunicationManager:585]: Set Bolus: Body - 50 
07-05 17:36:17.855 8059-8250/com.gxwtech.roundtrip2 D/MedtronicCommunicationManager: [Thread-4] DEBUG [info.nightscout.androidaps.plugins.PumpMedtronic.comm.MedtronicCommunicationManager:107]: Run command with Args: 
07-05 17:36:17.862 8059-8250/com.gxwtech.roundtrip2 I/RileyLinkCommunicationManager: [Thread-4] INFO  [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.RileyLinkCommunicationManager:74]: Sent:A7 41 20 20 42 00
07-05 17:36:17.964 8059-8250/com.gxwtech.roundtrip2 D/RFSpyReader: [Thread-4] DEBUG [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.ble.RFSpyReader:66]: Got data [null] at t==8804791
07-05 17:36:18.331 8059-8071/com.gxwtech.roundtrip2 D/RFTools: [Binder:8059_1] DEBUG [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.ble.RileyLinkBLE$1:78]: Response Count is 0E
07-05 17:36:18.573 8059-8088/com.gxwtech.roundtrip2 W/BluetoothGatt: onCharacteristicRead() - Device=00:07:80:B4:BD:30 handle=11 Status=0
07-05 17:36:18.730 8059-8250/com.gxwtech.roundtrip2 D/RFSpyReader: [Thread-4] DEBUG [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.ble.RFSpyReader:64]: Got data [4B 06 A9 6D 31 C9 5C 95 56 65 55 3A A5] at t==8805555
07-05 17:36:18.735 8059-8250/com.gxwtech.roundtrip2 I/RFSpy: [Thread-4] INFO  [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.ble.RFSpy:124]: writeToData: decoded radio response is A7 41 20 20 06 00
07-05 17:36:18.739 8059-8250/com.gxwtech.roundtrip2 I/RileyLinkCommunicationManager: [Thread-4] INFO  [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.RileyLinkCommunicationManager:87]: Received:A7 41 20 20 06 00
07-05 17:36:18.741 8059-8250/com.gxwtech.roundtrip2 D/MedtronicCommunicationManager: [Thread-4] DEBUG [info.nightscout.androidaps.plugins.PumpMedtronic.comm.MedtronicCommunicationManager:114]: Run command with Args: Got ACK response
07-05 17:36:18.750 8059-8250/com.gxwtech.roundtrip2 I/RileyLinkCommunicationManager: [Thread-4] INFO  [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.RileyLinkCommunicationManager:74]: Sent:A7 41 20 20 42 01 50 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
07-05 17:36:18.859 8059-8250/com.gxwtech.roundtrip2 D/RFSpyReader: [Thread-4] DEBUG [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.ble.RFSpyReader:66]: Got data [null] at t==8805684
07-05 17:36:19.894 8059-8071/com.gxwtech.roundtrip2 D/RFTools: [Binder:8059_1] DEBUG [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.ble.RileyLinkBLE$1:78]: Response Count is 0F
07-05 17:36:20.085 8059-8088/com.gxwtech.roundtrip2 W/BluetoothGatt: onCharacteristicRead() - Device=00:07:80:B4:BD:30 handle=11 Status=0
07-05 17:36:20.230 8059-8250/com.gxwtech.roundtrip2 D/RFSpyReader: [Thread-4] DEBUG [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.ble.RFSpyReader:64]: Got data [4B 07 A9 6D 31 C9 5C 95 C6 55 59 A9 95] at t==8807055
07-05 17:36:20.238 8059-8250/com.gxwtech.roundtrip2 I/RFSpy: [Thread-4] INFO  [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.ble.RFSpy:124]: writeToData: decoded radio response is A7 41 20 20 15 09
07-05 17:36:20.252 8059-8250/com.gxwtech.roundtrip2 I/RileyLinkCommunicationManager: [Thread-4] INFO  [info.nightscout.androidaps.plugins.PumpCommon.hw.rileylink.RileyLinkCommunicationManager:87]: Received:A7 41 20 20 15 09
07-05 17:36:20.261 8059-8250/com.gxwtech.roundtrip2 D/MedtronicCommunicationManager: [Thread-4] DEBUG [info.nightscout.androidaps.plugins.PumpMedtronic.comm.MedtronicCommunicationManager:117]: 2nd Response: PumpMessage [packetType=Invalid, address=(41 20 20 ), commandType=CommandNAK, messageBody=(UnknownMessageBody [txData=09 ])]
07-05 17:36:20.262 8059-8250/com.gxwtech.roundtrip2 D/MedtronicCommunicationManager: [Thread-4] DEBUG [info.nightscout.androidaps.plugins.PumpMedtronic.comm.MedtronicCommunicationManager:593]: Set Bolus: PumpMessage [response=NOT Acknowledged]

**Comment by andyrozman** [comment]
Tested on 554 by ticket owner @alternateal and tested on 523 by @jcwarrior. So closing the ticket as solved.
